# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherApp2-MVVM-singleView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherApp2-MVVM-singleView
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'RecastAI'

end
